import { z } from "zod";

const zodDateString = z.preprocess((arg) => {
    if (typeof arg == "string" || arg instanceof Date) return new Date(arg);
}, z.date());

export const FingerprintSchema = z.object({
    v: z.number(),
    tz: z.string(),
    dnt: z.boolean(),
    product: z.string(),
    osType: z.string(),
    app: z.string(),
    vendor: z.string(),
    cookies: z.boolean(),
    mem: z.number(),
    con: z.number(),
    lang: z.string(),
    plugins: z.string(),
    gpu: z.string(),
    fonts: z.string(),
    audioC: z.string(),
    analyser: z.string(),
    width: z.number(),
    height: z.number(),
    depth: z.number(),
    lStore: z.boolean(),
    sStore: z.boolean(),
    video: z.string(),
    audio: z.string(),
    media: z.string(),
    permissions: z.string(),
    audioFP: z.number(),
    webglFP: z.string(),
    canvasFP: z.number(),
    dP: z.number(),
    dF: z.number(),
    dW: z.number(),
    dC: z.number(),
    creation: zodDateString,
    uuid: z.string(),
    d: z.number(),
    osVersion: z.string(),
    vector: z.string(),
    userAgent: z.string(),
    serverTimeInMS: zodDateString,
    request: z.null(),
});
